"use strict";
angular.module('station.router',[]).config(function($stateProvider, $urlRouterProvider) {

  //默认跳转
  $urlRouterProvider.otherwise("/main/countShow/countArriveShow");

  $stateProvider
    .state("main", {
      url: "/main",
      templateUrl: 'views/main.html',
      controller:'mainCtrl'
    })
    .state("main.countDiffShow",{//对账差异展示情况
      url:'/countShow/countDiffShow',
      views:{
        'main':{
          templateUrl:'views/countShow/countDiffShow.html',
          controller:'countDiffCtrl'
        }
      }
    }).state("main.countAlarmShow",{//告警情况展示
      url:'/countShow/countAlarmShow',
      views:{
        'main':{
          templateUrl:'views/countShow/countAlarmShow.html',
          controller:'countAlarmCtrl'
        }
      }
    }).state("main.countArriveShow",{//对账到达情况展示
      url:'/countShow/countArriveShow',
      views:{
        'main':{
          templateUrl:'views/countShow/countArriveShow.html',
          controller:'countArriveCtrl'
        }
      }
    }).state("main.liveSettleDetailForm",{//全国汇总报表查询
      url:'/formOut/liveSettleDetailForm',
      views:{
        'main':{
          templateUrl:'views/formOut/liveSettleDetailForm.html',
          controller:'liveSettleDetailFormCtrl'
        }
      }
    }).state("main.liveBalanceSettleForm",{//全国汇总报表查询
      url:'/formOut/liveBalanceSettleForm',
      views:{
        'main':{
          templateUrl:'views/formOut/liveBalanceSettleForm.html',
          controller:'liveBalanceSettleFormCtrl'
        }
      }
    }).state("main.settleCheckRerun",{//文件下发状态查询
      url:'/businessControl/settleCheckRerun',
      views:{
        'main':{
          templateUrl:'views/businessControl/settleCheckRerun.html',
          controller:'settleCheckRerunCtrl'
        }
      }
    }).state("main.checkFileDownload",{//文件下发状态查询
      url:'/businessControl/checkFileDownload',
      views:{
        'main':{
          templateUrl:'views/businessControl/checkFileDownload.html',
          controller:'checkFileDownloadCtrl'
        }
      }
    }).state("main.fileSend",{//对账文件下发配置
      url:'/businessControl/fileSend',
      views:{
        'main':{
          templateUrl:'views/businessControl/fileSend.html',
          controller:'fileSendCtrl'
        }
      }
    }).state("main.reconDown",{//对账文件下载
      url:'/businessControl/reconDown',
      views:{
        'main':{
          templateUrl:'views/businessControl/reconDown.html',
          controller:'reconDownCtrl'
        }
      }
    }).state("main.reconRerun",{//对账文件重跑
      url:'/businessControl/reconRerun',
      views:{
        'main':{
          templateUrl:'views/businessControl/reconRerun.html',
          controller:'reconRerunCtrl'
        }
      }
    }).state("main.signInOut",{//签到签退状态展示
      url:'/businessShow/signInOut',
      views:{
        'main':{
          templateUrl:'views/businessShow/signInOut.html',
          controller:'signInOutCtrl'
        }
      }
    });

});